# Generated by Django 5.0 on 2024-03-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proId', models.CharField(max_length=3)),
                ('proName', models.CharField(max_length=200)),
                ('proGender', models.CharField(max_length=10)),
                ('proEmail', models.EmailField(max_length=254)),
                ('proDesignation', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Problem',
            },
        ),
    ]
