# Generated by Django 5.0 on 2024-04-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0002_alter_problem_proid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='proId',
            field=models.CharField(max_length=10),
        ),
    ]
