# Generated by Django 5.0 on 2024-04-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Docusername', models.CharField(max_length=10)),
                ('Docterpassword', models.CharField(max_length=200)),
                ('Docteremail', models.EmailField(max_length=254)),
                ('googlelink', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Docter',
            },
        ),
    ]
