# Generated by Django 5.0 on 2024-04-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docter',
            old_name='Docusername',
            new_name='Doctername',
        ),
    ]
