# Generated by Django 5.0 on 2024-04-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docter', '0002_rename_docusername_docter_doctername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docter',
            old_name='Doctername',
            new_name='Docterusername',
        ),
    ]
